api_token = "00_g3RHPadSNcAw3_w_Jw5NiFsw4Bx92fnnDSBIzH2"
application_name = "App_13"
audience_url = "https://cse-mait-1.com/SSO/metadata"
base_url = "okta.com"
org_name = "cse-mait-1"
sso_url = "https://cse-mait-1.com/sso"